SELECT TOP (1000) [CustomerId]
      ,[CompanyName]
      ,[Address]
      ,[City]
      ,[Region]
      ,[PostalCode]
      ,[Country]
      ,[Phone]
      ,[Fax]
      ,[Email]
  FROM [NWConsole_21_CW].[dbo].[Customers]